
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

# GameLogic Package 호출
from gamelogic import GameLogic, GameManager, RockPaperScissorsGame

# ------------------------Page UI-----------------------------------------
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/testUI/build/assets/frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1920x1080")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1080,
    width = 1920,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    960.0,
    540.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    959.0,
    563.0,
    image=image_image_2
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=372.0,
    y=726.0,
    width=372.190185546875,
    height=224.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=774.905029296875,
    y=726.0,
    width=372.190185546875,
    height=224.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=1178.0,
    y=726.0,
    width=372.190185546875,
    height=224.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=1501.0,
    y=147.0,
    width=168.0,
    height=66.0
)

canvas.create_rectangle(
    377.0,
    316.0,
    738.0,
    691.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    1183.0,
    316.0,
    1544.0,
    691.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    1185.0,
    253.0,
    anchor="nw",
    text="나",
    fill="#000000",
    font=("Inter Bold", 40 * -1)
)

canvas.create_text(
    385.0,
    253.0,
    anchor="nw",
    text="상대방",
    fill="#000000",
    font=("Inter Bold", 40 * -1)
)

canvas.create_rectangle(
    769.0,
    419.0,
    1151.0,
    620.0,
    fill="#FFFFFF",
    outline="")
window.resizable(False, False)
window.mainloop()
